---
version: 2.0
builds:
  build-all:
    commands: [ "/bin/sh", "-c", "cd /usr/src/github.com/ROCm/device-config-manager && make build-all"]
    owners: ["email:nkomarla@amd.com"]
    area:
    sub-area:
    feature:

  build-device-config-manager-docker-ubi9:
    commands: ["sh", "-c", "cd /usr/src/github.com/ROCm/device-config-manager && HOURLY_TAG_LABEL=$RELEASE make all"]
    owners: ["email:nkomarla@amd.com"]
    artifacts:
        - /device-config-manager/docker/obj/config-manager-ubi9-latest.tgz

  build-helm-artifact:
    commands: ["sh", "-c", "cd /usr/src/github.com/ROCm/device-config-manager && make helm-build"]
    owners: ["email:nkomarla@amd.com"]
    artifacts:
        - /device-config-manager/helm-charts/device-config-manager-charts-v1.3.1.tgz
  
  docs-sanity:
    commands: [ "sh", "-c", "cd /usr/src/github.com/ROCm/device-config-manager && make docs"]
    owners: ["email:nkomarla@amd.com"]

targets:
  api-checks:
    commands: [ "/bin/sh", "-c", "cd /usr/src/github.com/ROCm/device-config-manager && \
                                    make checks"]
    owners: ["email:nkomarla@amd.com"]
    area:
    sub-area:
    feature:
    build-dependencies:
        - build-device-config-manager-docker-ubi9
        - build-helm-artifact
        - docs-sanity
        - build-all

image:
  bind_dir: "/device-config-manager"
  work_dir: "/device-config-manager"

jobs:
  asset-build:
    labels: ["CI-Sanity-Build"]
