apiVersion: v2
name: device-config-manager-charts
description: A Helm chart for AMD GPU Device Config Manager

type: application
version: v1.5.2
appVersion: "v1.5.2"
maintainers:
- email: nkomarla@amd.com
  name: Nikhil S K