---
version: 2.0
targets:
  copy-device-config-manager-artifacts:
    commands: ["sh", "-c", "cd /device-config-manager && /configmanager-asset-push.sh"]
    owners: ["email:nkomarla@amd.com"]
    area:
    sub-area:
    feature:
    build-dependencies:
      - build-device-config-manager-docker-ubi9
      - build-helm-artifact

image:
  bind_dir: "/go/src/github.com/ROCm/device-config-manager"
  work_dir: "/go/src/github.com/ROCm/device-config-manager"